### ISSUE TITLE
Cannot open the downloadable link

### ISSUE THREAD

**Issue by zwx8981** [DXOMARK-Research/PIQ2023#1]
Hi, thanks for your great work! It seems that the downloadable link is not working, can you check this? Thank you!

**Comment by nicolasch96** [comment]
Hello,

We apologize for the inconvenience. We are facing some technical issues with the automated email reply. We will come back to you as soon as it's fixed.

Best,

Nicolas

**Comment by zwx8981** [comment]
@nicolasch96 Thanks for your reply!

**Comment by nichahine** [comment]
Hello,

The automatic email reply and the link are now functional. 

Please if you find any new problems, do not hesitate to open a new issue.

Do not hesitate to share any tests you do on the dataset with us! We wish PIQ23 to be a good contribution to the community

Best,

Nicolas
