### ISSUE TITLE
"Page Not Found" Error When Clicking the Link in the Reply Email

### ISSUE THREAD

**Issue by CanranJin** [DXOMARK-Research/PIQ2023#11]
Thank you for your great work. However, when I attempt to download the dataset using the link provided in the auto-reply email, I encounter a "Page Not Found" error. The message states, "The page could not be found on the server or you may not be allowed to view it." Could you please look into this issue?
![image](https://github.com/user-attachments/assets/e176bf08-1a2f-49e5-bd51-086c3bc1b823)

**Comment by nicolasch96** [comment]
Hello,

We'll check the problem and come back to you.

Thank you for your interest in our work.

Nicolas

**Comment by nicolasch96** [comment]
Hello,

It should be working now.

If you don't receive the download file immediately please try to refresh the link or use a different browser. 

Try to launch a new request. Also, please use the link within 24 hours.

I will close this issue, if you have any problems do not hesitate to open it again.

Best,

Nicolas
