### ISSUE TITLE
About the training stratage

### ISSUE THREAD

**Issue by chencn2020** [DXOMARK-Research/PIQ2023#4]
Hi, I find that some jod-score is negative.

I'd like to know when you training a IQA model, like HyperIQA, do you do some process with jod scores, or do you just let the model predict negative jod.

Looking forward to your replay :)

**Comment by nicolasch96** [comment]
Hello,

Yes since the scores are on a JOD scale (Just Objectionable Difference), they don't need to be strictly positive. Since the scores are open the prediction can be negative yes, we don't use any sigmoid here.

I hope I answered your question.

Nicolas
