### ISSUE TITLE
About the 1344

### ISSUE THREAD

**Issue by chencn2020** [DXOMARK-Research/PIQ2023#7]
Hi, thanks for your great work!

I'd like to inquire that what the meaning of the 1344 in SEM-HyperIQA-SO 1344 (224*6) .

Dose the SEM-HyperIQA-SO get the full image as the input ?

**Comment by nichahine** [comment]
Hello,

This represents the size of the crop. We do not input the full ROI to the model but a random crop. The random crop size here is 1344 x 1344. For hyperiqa architecture it has to be a multiple of 224. For MUSIQ, DBCNN it can be any size. You can use the full image if you want (By full image I mean the full ROI, so for overall it's a full image, for details and exposure it's the face ROI)
